# Splunk Universal Forwarder — inputs.conf  (Win10 endpoint)
# Path: ...\SplunkUniversalForwarder\etc\system\local\inputs.conf
# Ships Windows Security auth events + the Sysmon channel into the `endpoint` index.

[WinEventLog://Security]
start_from = oldest
current_only = false
index = endpoint

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
start_from = oldest
current_only = false
renderXml = true
index = endpoint
